---
name: Deploy

on:
  push:
    branches-ignore:
      - 'repo-helper-update'
      - 'pre-commit-ci-update-config'
      - 'imgbot'
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v3"

      - name: Setup Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: |
          set +e
          python3 get_data.py
          set -e
          python3 plot.py

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: books/
          force_orphan: true
